### ISSUE TITLE
set certificate by passing a string instead of a file location

### ISSUE THREAD

**Issue by pdpinch** [mitodl/mit-moira#1]
In deployment environments like Heroku it's inconvenient to store certificates as a file on disk. Our approach in other apps has been to put the certificate into a environment variable and then pass it to a library like mit-moira as a string.

**Comment by mbertrand** [comment]
MIT-Moira is making use of the `zeep` library, which in turn uses the `requests` library, which only accepts filepaths for certificates.  Closing this and replacing with https://github.com/mitodl/odl-video-service/issues/142
